output: main.o
	g++ main.o -Wall -o output
	./output

Alg.o: main.cpp
	g++ -c main.cpp

clean:
	rm -f *.o output
	rm -f *.o alg
	rm -f *.txt matriz
	rm -f *.txt matriz2
	rm -f *.txt resultado_strassen
	rm -f *.txt resultado_traspuesta
	rm -f *.txt resultado_normal